services:
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    networks:
      - app_net

  frontend:
    build:
      context: ./comic_viewer
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
