version: "3.9"

services:
  backend:
    image: knorrsche/comic-to-narration-backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    working_dir: /app
    command: uvicorn src.Components.backend:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONPATH=/app
    networks:
      - app_net

  frontend:
    image: knorrsche/comic-to-narration-frontend:latest
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./comic_viewer/src:/app/src
      - ./comic_viewer/public:/app/public
      - ./comic_viewer/package.json:/app/package.json
      - ./comic_viewer/package-lock.json:/app/package-lock.json
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
