from datasets import load_dataset
from PIL import Image
import numpy as np


def read_image(path_to_image):
    with open(path_to_image, "rb") as file:
        image = Image.open(file).convert("L").convert("RGB")
        image = np.array(image)
    return image


if __name__ == "__main__":
    dataset = load_dataset("ragavsachdeva/popmanga_test",
                           trust_remote_code=True)  # the first time you run this, it will download the images from mangaplus
    split = "seen"  # "unseen"
    for b, example in enumerate(dataset[split]):
        image_path, magi_annotations, character_clusters, text_char_matches, text_tail_matches, text_classification, character_names = example.values()
        image = read_image(image_path)
        character_bboxes = [bbox for bbox, label in
                            zip(magi_annotations["bboxes_as_x1y1x2y2"], magi_annotations["labels"]) if label == 0]
        text_bboxes = [bbox for bbox, label in zip(magi_annotations["bboxes_as_x1y1x2y2"], magi_annotations["labels"])
                       if label == 1]
        panel_bboxes = [bbox for bbox, label in zip(magi_annotations["bboxes_as_x1y1x2y2"], magi_annotations["labels"])
                        if label == 2]  # these are generated by the model (included for convenience)
        tail_bboxes = [bbox for bbox, label in zip(magi_annotations["bboxes_as_x1y1x2y2"], magi_annotations["labels"])
                       if label == 3]